name: matrix-demo

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    name: my-build-job
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
     matrix:
      include:
       - empId: 1
         empName: Bilal
       - empId: 2
         empName: Waqas
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello ${{ matrix.empId}} - ${{matrix.empName}}
